src/objects/Action__c.object
<CustomObject>
    <description>Object to create update field or send email actions.</description>
    <fields>
        <fullName>Auto_Task__c</fullName>
        <description>Master detail relationship to an Auto Task</description>
        <label>Auto Task</label>
        <referenceTo>Auto_Task__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Field_To_Update__c</fullName>
        <description>Field to update when auto task is ran.</description>
        <label>Field To Update</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Layout__c</fullName>
        <description>Layout Name</description>
        <label>Layout</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Value__c</fullName>
        <description>New field value for field update.</description>
        <label>New Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object for which field will be updated.</description>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recipient_s_Email_Address__c</fullName>
        <description>Email address of recipient</description>
        <inlineHelpText>If not a survey and need more than one email address, separate with semicolon. (Ex. test@email.com;test2@email.com)</inlineHelpText>
        <label>Recipient&apos;s Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <description>To store record type name</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email_From__c</fullName>
        <description>Organization wide email address from where email will be sent from.</description>
        <label>Send Email From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email_To__c</fullName>
        <description>Person to whom email will be sent to.</description>
        <label>Send Email To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case Creator</fullName>
                </value>
                <value>
                    <fullName>Case Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Survey_To__c</fullName>
        <label>Send Survey To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case Creator</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <description>Name of survey to send.</description>
        <label>Survey Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Name__c</fullName>
        <description>Name of template that will be used to send email.</description>
        <label>Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Auto_Task__c.object
<CustomObject>
    <description>Object to relate &quot;RO &amp; OAE Templates&quot; and &quot;Actions&quot;</description>
    <label>Auto Task</label>
    <nameField>
        <label>Auto Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auto Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DisplayActionsController_AC.cls
/*********************************************************************
Class Name: SearchROAETemplates_AC
Created By: Mission Possible - Robert Jaramillo 
Created On: 04-13-2020
Description: Controller for DisplayActions lightning component.
*********************************************************************/
public class DisplayActionsController_AC {
    
    @AuraEnabled
    public Boolean hasError; //Used to verify any exception occurred
    
    @AuraEnabled
    public String errorMessage; //Used to hold the exception message
    
    @AuraEnabled
    public String userMessage; //Used to hold the custom error message
    
    @AuraEnabled
    public DisplayActionsController_AC controller;
    
    @AuraEnabled
    public static List<Action__c> getActions(String recordId, String recordType) {
        String actionRecordTypeId;
        String orderByField;
        
        if(recordType.equals(RecordTypeConstants_AC.UPDATE_FIELD_RT)) {
            actionRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.UPDATE_FIELD_RT).getRecordTypeId();
            orderByField = 'Object__c';
        }else if(recordType.equals(RecordTypeConstants_AC.SEND_EMAIL_RT)) {
            actionRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_EMAIL_RT).getRecordTypeId();
            orderByField = 'Name';
        }else {
            actionRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_SURVEY_RT).getRecordTypeId();
            orderByField = 'Name';
        }

		String query = 'SELECT Id, Name, Object__c, Record_Type_Name__c, Field_To_Update__c, New_Value__c, Layout__c, Template_Name__c, ' +
                'Send_Email_To__c, Send_Email_From__c, Survey_Name__c, Send_Survey_To__c, Recipient_s_Email_Address__c ' + 
            'FROM Action__c WHERE Auto_Task__c =: recordId AND RecordTypeId =: actionRecordTypeId ORDER BY ' + orderByField + ' ASC';
        return Database.query(query);
    }
    
    @AuraEnabled
    public static DisplayActionsController_AC deleteAction(String recordId) {
        DisplayActionsController_AC controller = new DisplayActionsController_AC();
        
        try{
            List<Action__c> actionToDelete = [SELECT Id FROM Action__c WHERE Id =: recordId];
            if(!actionToDelete.isEmpty()) {
                delete actionToDelete;
            }
        }catch(Exception e) {
            controller.hasError = true;
            controller.errorMessage = 'Exception:' + e.getMessage();
            ApplicationLogs__c appLog = new ApplicationLogs__c(Event_Type__c = 'DELETE_ACTION' , Class_Name__c = 'DisplayActionsController_AC', 
                                                               Error_Message__c = e.getMessage(), StackTrace__c	= e.getStackTraceString(), 
                                                               Line_Number__c = String.valueOf(e.getLineNumber()));
            insert appLog;
        }
        return controller;
    }
    
}