src/objects/Action__c.object
<CustomObject>
    <description>Object to create update field or send email actions.</description>
    <fields>
        <fullName>Auto_Task__c</fullName>
        <description>Master detail relationship to an Auto Task</description>
        <label>Auto Task</label>
        <referenceTo>Auto_Task__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Field_To_Update_API_Name__c</fullName>
        <description>To store API name of field to update.</description>
        <label>Field To Update API Name</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_To_Update__c</fullName>
        <description>Field to update when auto task is ran.</description>
        <label>Field To Update</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Layout__c</fullName>
        <description>Layout Name</description>
        <label>Layout</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Value__c</fullName>
        <description>New field value for field update.</description>
        <label>New Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object for which field will be updated.</description>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recipient_s_Email_Address__c</fullName>
        <description>Email address of recipient</description>
        <inlineHelpText>If not a survey and need more than one email address, separate with semicolon. (Ex. test@email.com;test2@email.com)</inlineHelpText>
        <label>Recipient&apos;s Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email_To__c</fullName>
        <description>Person to whom email will be sent to.</description>
        <label>Send Email To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case Creator</fullName>
                </value>
                <value>
                    <fullName>Case Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Survey_To__c</fullName>
        <label>Send Survey To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case Creator</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <description>Name of survey to send.</description>
        <label>Survey Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Name__c</fullName>
        <description>Name of template that will be used to send email.</description>
        <label>Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Auto_Task__c.object
<CustomObject>
    <description>Object to relate &quot;RO &amp; OAE Templates&quot; and &quot;Actions&quot;</description>
    <label>Auto Task</label>
    <nameField>
        <label>Auto Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auto Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateActionController_AC_Test.cls
/*********************************************************************
Class Name: CreateActionController_AC_Test
Created By: MST - Robert Jaramillo 
Created On: 05-13-2020
Description: Test class for CreateActionController_AC.
*********************************************************************/
@isTest
public class CreateActionController_AC_Test {

    @testSetup
    static void setup() {
        String sendEmailRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_EMAIL_RT).getRecordTypeId();
        String sendSurveyRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_SURVEY_RT).getRecordTypeId();
        
        Auto_Task__c newAutoTask = new Auto_Task__c(Name = 'AutoTask-0000');
        insert newAutoTask;
        
        List<Action__c> actionList = new List<Action__c>();
        Action__c newAction = new Action__c(Name = 'Test Action', Auto_Task__c = newAutoTask.Id, Field_To_Update__c = 'Status', Object__c = 'Case',
                                            Field_To_Update_API_Name__c = 'Status', Layout__c = 'ARSC Read Only', New_Value__c = 'Pending');
        actionList.add(newAction);
        Action__c newEmailAction = new Action__c(Name = 'Test Action', Auto_Task__c = newAutoTask.Id, Template_Name__c = 'Test Template',
                                            Send_Email_To__c = 'Other', Recipient_s_Email_Address__c = 'test@email.com', RecordTypeId = sendEmailRecordTypeId);
        actionList.add(newEmailAction);
        Action__c newSurveyAction = new Action__c(Name = 'Test Action', Auto_Task__c = newAutoTask.Id, Survey_Name__c = 'Test Survey',
                                            Send_Survey_To__c = 'Other', Recipient_s_Email_Address__c = 'test@email.com', RecordTypeId = sendSurveyRecordTypeId);
        actionList.add(newSurveyAction);
        insert actionList;
    }
    
    static testMethod void getCaseFieldsTest() {
        CreateActionController_AC controller = new CreateActionController_AC();
        List<Action__c> actionList = [SELECT Id FROM Action__c];
        Test.startTest();
        controller = CreateActionController_AC.getCaseFields(actionList[0].Id);
        Test.stopTest();
        
        System.assertEquals(false, controller.actionRecord == null, 'Action record not found.');
    }
    
    static testMethod void getOrgWideEmailsTest() {
        CreateActionController_AC controller = new CreateActionController_AC();
        List<Action__c> actionList = [SELECT Id FROM Action__c];
        Test.startTest();
        controller = CreateActionController_AC.getOrgWideEmailsAndAction(actionList[0].Id);
        Test.stopTest();
        
        System.assertEquals(false, controller.actionRecord == null, 'Action record not found.');
    }
    
    static testMethod void saveUpdateFieldActionTest() {
        CreateActionController_AC controller = new CreateActionController_AC();
        List<Auto_Task__c> autoTaskList = [SELECT Id, Name FROM Auto_Task__c];
        
        String newActionName = 'Test Action';
        String autoTaskId = autoTaskList[0].Id;
        String objectToUpdate = 'Case';
        String pageLayout = 'ARSC Read Only';
        String fieldApiSelected = 'Status';
        String newValue = 'Resolved';
        String actionRecId = null;
        String editMode = 'false';
        
        Test.startTest();
        controller = CreateActionController_AC.saveUpdateFieldAction(newActionName, autoTaskId, objectToUpdate, 
                                                                         pageLayout, fieldApiSelected, newValue, actionRecId, editMode);
        Test.stopTest();
        System.assertEquals(false, controller.userMessage == null, 'User message is empty.');
    }
    
    static testMethod void saveUpdateFieldActionEditModeTest() {
        CreateActionController_AC controller = new CreateActionController_AC();
        List<Auto_Task__c> autoTaskList = [SELECT Id, Name FROM Auto_Task__c];
        List<Action__c> actionList = [SELECT Id FROM Action__c];
        
        String newActionName = 'Test Action';
        String autoTaskId = autoTaskList[0].Id;
        String objectToUpdate = 'Case';
        String pageLayout = 'ARSC Read Only';
        String fieldApiSelected = 'Subject';
        String newValue = 'Resolved';
        String actionRecId = actionList[0].Id;
        String editMode = 'true';
        
        Test.startTest();
        controller = CreateActionController_AC.saveUpdateFieldAction(newActionName, autoTaskId, objectToUpdate, 
                                                                         pageLayout, fieldApiSelected, newValue, actionRecId, editMode);
        Test.stopTest();
        System.assertEquals(true, controller.userMessage == null, 'User message is not empty.');
    }
    
    static testMethod void saveUpdateFieldActionWithExceptionTest() {
        CreateActionController_AC controller = new CreateActionController_AC();
        
        String newActionName = 'Test Action';
        String autoTaskId = null;
        String objectToUpdate = 'Case';
        String pageLayout = 'ARSC Read Only';
        String fieldApiSelected = 'Subject';
        String newValue = 'Resolved';
        String actionRecId = null;
        String editMode = 'false';
        
        Test.startTest();
        controller = CreateActionController_AC.saveUpdateFieldAction(newActionName, autoTaskId, objectToUpdate, 
                                                                         pageLayout, fieldApiSelected, newValue, actionRecId, editMode);
        Test.stopTest();
        System.assertEquals(true, controller.hasError, 'Exception was not caught.');
    }
    
    static testMethod void saveSendEmailActionTest() {
        CreateActionController_AC controller = new CreateActionController_AC();
        String sendEmailRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_EMAIL_RT).getRecordTypeId();
        List<Auto_Task__c> autoTaskList = [SELECT Id, Name FROM Auto_Task__c];
        
        String newActionName = 'Test Send Email Action';
        String autoTaskId = autoTaskList[0].Id;
        String templateName = 'Test Template';
        String sendEmailFrom = 'ARSC';
        String sendEmailTo = 'Other';
        String recipientsEmail = 'test@email.com';
        String actionRecId = null;
        String editMode = 'false';
        
        Test.startTest();
        controller = CreateActionController_AC.saveSendEmailAction(newActionName, autoTaskId, templateName, sendEmailFrom,
                                                                         sendEmailTo, recipientsEmail, actionRecId, editMode);
        Test.stopTest();
        System.assertEquals(false, controller.userMessage == null, 'User message is empty.');
    }
    
    static testMethod void saveSendEmailActionEditModeTest() {
        CreateActionController_AC controller = new CreateActionController_AC();
        String sendEmailRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_EMAIL_RT).getRecordTypeId();
        
        List<Auto_Task__c> autoTaskList = [SELECT Id, Name FROM Auto_Task__c];
        List<Action__c> actionList = [SELECT Id FROM Action__c WHERE RecordTypeId =: sendEmailRecordTypeId];
        
        String newActionName = 'Test Send Email Action';
        String autoTaskId = autoTaskList[0].Id;
        String templateName = 'Test Template';
        String sendEmailFrom = 'ARSC';
        String sendEmailTo = 'Other';
        String recipientsEmail = 'test@email.com';
        String actionRecId = actionList[0].Id;
        String editMode = 'true';
        
        Test.startTest();
        controller = CreateActionController_AC.saveSendEmailAction(newActionName, autoTaskId, templateName, sendEmailFrom, 
                                                                         sendEmailTo, recipientsEmail, actionRecId, editMode);
        Test.stopTest();
        System.assertEquals(true, controller.userMessage == null, 'User message is not empty.');
    }
    
    static testMethod void saveSendEmailActionWithExceptionTest() {
        CreateActionController_AC controller = new CreateActionController_AC();        
       
        String newActionName = 'Test Send Email Action';
        String autoTaskId = null;
        String templateName = 'Test Template';
        String sendEmailFrom = 'ARSC';
        String sendEmailTo = 'Other';
        String recipientsEmail = 'test@email.com';
        String actionRecId = null;
        String editMode = 'false';
        
        Test.startTest();
        controller = CreateActionController_AC.saveSendEmailAction(newActionName, autoTaskId, templateName, sendEmailFrom,
                                                                         sendEmailTo, recipientsEmail, actionRecId, editMode);
        Test.stopTest();
        System.assertEquals(true, controller.hasError, 'Exception was not caughtt.');
    }
    
    static testMethod void saveSendSurveyActionTest() {
        CreateActionController_AC controller = new CreateActionController_AC();
        String sendSurveyRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_SURVEY_RT).getRecordTypeId();
        List<Auto_Task__c> autoTaskList = [SELECT Id, Name FROM Auto_Task__c];
        
        String newActionName = 'Test Send Email Action';
        String autoTaskId = autoTaskList[0].Id;
        String surveyName = 'Test Survey';
        String sendSurveyTo = 'Other';
        String recipientsEmail = 'test@email.com';
        String actionRecId = null;
        String editMode = 'false';
        
        Test.startTest();
        controller = CreateActionController_AC.saveSendSurveyAction(newActionName, autoTaskId, surveyName, sendSurveyTo, 
                                                                    recipientsEmail, actionRecId, editMode);
        Test.stopTest();
        System.assertEquals(false, controller.userMessage == null, 'User message is empty.');
    }
    
    static testMethod void saveSendSurveyActionEditModeTest() {
        CreateActionController_AC controller = new CreateActionController_AC();
        String sendSurveyRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_SURVEY_RT).getRecordTypeId();
        
        List<Auto_Task__c> autoTaskList = [SELECT Id, Name FROM Auto_Task__c];
        List<Action__c> actionList = [SELECT Id FROM Action__c WHERE RecordTypeId =: sendSurveyRecordTypeId];
        
        String newActionName = 'Test Send Email Action';
        String autoTaskId = autoTaskList[0].Id;
        String surveyName = 'Test Survey';
        String sendSurveyTo = 'Other';
        String recipientsEmail = 'test@email.com';
        String actionRecId = actionList[0].Id;
        String editMode = 'true';
        
        Test.startTest();
        controller = CreateActionController_AC.saveSendSurveyAction(newActionName, autoTaskId, surveyName, sendSurveyTo, 
                                                                    recipientsEmail, actionRecId, editMode);
        Test.stopTest();
        System.assertEquals(true, controller.userMessage == null, 'User message is not empty.');
    }
    
    static testMethod void saveSendSurveyActionWithExceptionTest() {
        CreateActionController_AC controller = new CreateActionController_AC();
        
        String newActionName = 'Test Send Email Action';
        String autoTaskId = null;
        String surveyName = 'Test Survey';
        String sendSurveyTo = 'Other';
        String recipientsEmail = 'test@email.com';
        String actionRecId = null;
        String editMode = 'false';
        
        Test.startTest();
        controller = CreateActionController_AC.saveSendSurveyAction(newActionName, autoTaskId, surveyName, sendSurveyTo, 
                                                                    recipientsEmail, actionRecId, editMode);
        Test.stopTest();
        System.assertEquals(true, controller.hasError, 'Exception was not caught.');
    }
}