src/objects/Action__c.object
<CustomObject>
    <description>Object to create update field or send email actions.</description>
    <fields>
        <fullName>Auto_Task__c</fullName>
        <description>Master detail relationship to an Auto Task</description>
        <label>Auto Task</label>
        <referenceTo>Auto_Task__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Field_To_Update_API_Name__c</fullName>
        <description>To store API name of field to update.</description>
        <label>Field To Update API Name</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_To_Update__c</fullName>
        <description>Field to update when auto task is ran.</description>
        <label>Field To Update</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Layout__c</fullName>
        <description>Layout Name</description>
        <label>Layout</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Value__c</fullName>
        <description>New field value for field update.</description>
        <label>New Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object for which field will be updated.</description>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recipient_s_Email_Address__c</fullName>
        <description>Email address of recipient</description>
        <inlineHelpText>If not a survey and need more than one email address, separate with semicolon. (Ex. test@email.com;test2@email.com)</inlineHelpText>
        <label>Recipient&apos;s Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email_To__c</fullName>
        <description>Person to whom email will be sent to.</description>
        <label>Send Email To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case Creator</fullName>
                </value>
                <value>
                    <fullName>Case Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Survey_To__c</fullName>
        <label>Send Survey To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case Creator</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <description>Name of survey to send.</description>
        <label>Survey Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Name__c</fullName>
        <description>Name of template that will be used to send email.</description>
        <label>Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Auto_Task__c.object
<CustomObject>
    <description>Object to relate &quot;RO &amp; OAE Templates&quot; and &quot;Actions&quot;</description>
    <label>Auto Task</label>
    <nameField>
        <label>Auto Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auto Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DisplayActionsController_AC_Test.cls
/*********************************************************************
Class Name: DisplayActionsController_AC_Test
Created By: MST - Robert Jaramillo 
Created On: 05-13-2020
Description: Test class for DisplayActionsController_AC.
*********************************************************************/
@isTest
public class DisplayActionsController_AC_Test {
    
    @testSetup
    static void setup() {
        String fieldUpdateRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.UPDATE_FIELD_RT).getRecordTypeId();
        String sendEmailRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_EMAIL_RT).getRecordTypeId();
        String sendSurveyRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_SURVEY_RT).getRecordTypeId();
        
        Auto_Task__c newAutoTask = new Auto_Task__c(Name = 'AutoTask-0000');
        insert newAutoTask;
        
        List<Action__c> actionList = new List<Action__c>();
        Action__c newAction = new Action__c(Name = 'Test Action', Auto_Task__c = newAutoTask.Id, Field_To_Update__c = 'Status', Object__c = 'Case',
                                            Field_To_Update_API_Name__c = 'Status', Layout__c = 'ARSC Read Only', New_Value__c = 'Pending',
                                           RecordTypeId = fieldUpdateRecordTypeId);
        actionList.add(newAction);
        Action__c newEmailAction = new Action__c(Name = 'Test Action', Auto_Task__c = newAutoTask.Id, Template_Name__c = 'Test Template',
                                            Send_Email_To__c = 'Other', Recipient_s_Email_Address__c = 'test@email.com', RecordTypeId = sendEmailRecordTypeId);
        actionList.add(newEmailAction);
        Action__c newSurveyAction = new Action__c(Name = 'Test Action', Auto_Task__c = newAutoTask.Id, Survey_Name__c = 'Test Survey',
                                            Send_Survey_To__c = 'Other', Recipient_s_Email_Address__c = 'test@email.com', RecordTypeId = sendSurveyRecordTypeId);
        actionList.add(newSurveyAction);
        insert actionList;
    }

    static testMethod void getActionsFieldUpdateTest() {
        List<Action__c> actionList = new List<Action__c>();
        List<Auto_Task__c> autoTaskList = [SELECT Id FROM Auto_Task__c];
        
        Test.startTest();
        actionList = DisplayActionsController_AC.getActions(autoTaskList[0].Id, RecordTypeConstants_AC.UPDATE_FIELD_RT);
        Test.stopTest();
        
        System.assertEquals(false, actionList.isEmpty(), 'List returned is empty.');
    }
    
    static testMethod void getActionsSendEmailTest() {
        List<Action__c> actionList = new List<Action__c>();
        List<Auto_Task__c> autoTaskList = [SELECT Id FROM Auto_Task__c];
        
        Test.startTest();
        actionList = DisplayActionsController_AC.getActions(autoTaskList[0].Id, RecordTypeConstants_AC.SEND_EMAIL_RT);
        Test.stopTest();
        
        System.assertEquals(false, actionList.isEmpty(), 'List returned is empty.');
    }
    
    static testMethod void getActionsSendSurveyTest() {
        List<Action__c> actionList = new List<Action__c>();
        List<Auto_Task__c> autoTaskList = [SELECT Id FROM Auto_Task__c];
        
        Test.startTest();
        actionList = DisplayActionsController_AC.getActions(autoTaskList[0].Id, RecordTypeConstants_AC.SEND_SURVEY_RT);
        Test.stopTest();
        
        System.assertEquals(false, actionList.isEmpty(), 'List returned is empty.');
    }
    
    static testMethod void deleteActionTest() {
        DisplayActionsController_AC controller = new DisplayActionsController_AC();
        List<Action__c> actionList = [SELECT Id FROM Action__c];
        
        Test.startTest();
        controller = DisplayActionsController_AC.deleteAction(actionList[0].Id);
        Test.stopTest();
        
        System.assertEquals(null, controller.hasError, 'An exception was caught.');
    }
}