src/objects/Action__c.object
<CustomObject>
    <description>Object to create update field or send email actions.</description>
    <fields>
        <fullName>Auto_Task__c</fullName>
        <description>Master detail relationship to an Auto Task</description>
        <label>Auto Task</label>
        <referenceTo>Auto_Task__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Field_To_Update_API_Name__c</fullName>
        <description>To store API name of field to update.</description>
        <label>Field To Update API Name</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_To_Update__c</fullName>
        <description>Field to update when auto task is ran.</description>
        <label>Field To Update</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Layout__c</fullName>
        <description>Layout Name</description>
        <label>Layout</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Value__c</fullName>
        <description>New field value for field update.</description>
        <label>New Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object for which field will be updated.</description>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recipient_s_Email_Address__c</fullName>
        <description>Email address of recipient</description>
        <inlineHelpText>If not a survey and need more than one email address, separate with semicolon. (Ex. test@email.com;test2@email.com)</inlineHelpText>
        <label>Recipient&apos;s Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email_From__c</fullName>
        <description>Organization wide email address from where email will be sent from.</description>
        <label>Send Email From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email_To__c</fullName>
        <description>Person to whom email will be sent to.</description>
        <label>Send Email To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case Creator</fullName>
                </value>
                <value>
                    <fullName>Case Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Survey_To__c</fullName>
        <label>Send Survey To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case Creator</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <description>Name of survey to send.</description>
        <label>Survey Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Name__c</fullName>
        <description>Name of template that will be used to send email.</description>
        <label>Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Auto_Task__c.object
<CustomObject>
    <description>Object to relate &quot;RO &amp; OAE Templates&quot; and &quot;Actions&quot;</description>
    <label>Auto Task</label>
    <nameField>
        <label>Auto Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auto Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RunAutoTaskController_AC_Test.cls
/*********************************************************************
Class Name: RunAutoTaskController_AC_Test
Created By: MST - Robert Jaramillo 
Created On: 05-14-2020
Description: Test class for RunAutoTaskController_AC.
*********************************************************************/
@isTest
public class RunAutoTaskController_AC_Test {

    @testSetup
    static void setup() {
        String recordType = System.Label.Task_RO_OAE_RT;
        String taskRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get(recordType).getRecordTypeId();
        String updateFieldRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.UPDATE_FIELD_RT).getRecordTypeId();
        String sendEmailRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_EMAIL_RT).getRecordTypeId();
        String sendSurveyRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_SURVEY_RT).getRecordTypeId();
        String personAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('02 - Engaged Student').getRecordTypeId();
        String ARSCRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('ARSC').getRecordTypeId();
        
        Account testAcc = new Account(FirstName = 'Test', LastName = 'Account', RecordTypeId = personAccountRecordTypeId);
        insert testAcc;
        
        Case testCase = new Case(Status = 'Open', Subject = 'Test Case', ROAE_Type__c = 'ACADEMIC RECORD',
                                            ROAE_Subtype__c = 'Academic Status: Advisement', RecordTypeId = ARSCRecordTypeId);
        insert testCase;
        
        Task testTask = new Task(Subject = 'Test Subject', ROAE_Assignment_Group__c = 'RO', ROAE_Task_Type__c = 'APA', 
                                 Status = 'Resolved', WhatId = testCase.Id, RecordTypeId = taskRecordTypeId);
        insert testTask;
                
        Auto_Task__c newAutoTask = new Auto_Task__c(Name = 'AutoTask-0000');
        insert newAutoTask;
        
        List<Action__c> actionList = new List<Action__c>();
        Action__c caseAction = new Action__c(Name = 'Test Action', Auto_Task__c = newAutoTask.Id, Field_To_Update__c = 'Status', Object__c = 'Case',
                                            Field_To_Update_API_Name__c = 'Status', Layout__c = 'ARSC Read Only', New_Value__c = 'Pending', 
                                            RecordTypeId = updateFieldRecordTypeId);
        actionList.add(caseAction);
        
        Action__c caseAction2 = new Action__c(Name = 'Test Action 2', Auto_Task__c = newAutoTask.Id, Field_To_Update__c = 'Rush', Object__c = 'Case',
                                            Field_To_Update_API_Name__c = 'Rush__c', Layout__c = 'ARSC Read Only', New_Value__c = 'false', 
                                            RecordTypeId = updateFieldRecordTypeId);
        actionList.add(caseAction2);
        
        Action__c newTaskAction = new Action__c(Name = 'Task - Update Status', Auto_Task__c = newAutoTask.Id, Field_To_Update__c = 'Status', Object__c = 'Task',
                                            Field_To_Update_API_Name__c = 'Status', Layout__c = 'RO & OAE', New_Value__c = 'Pending', 
                                                RecordTypeId = updateFieldRecordTypeId);
        actionList.add(newTaskAction);
        
        Action__c newTaskAction2 = new Action__c(Name = 'Task - Update Rush', Auto_Task__c = newAutoTask.Id, Field_To_Update__c = 'Rush', Object__c = 'Task',
                                            Field_To_Update_API_Name__c = 'ROAE_Rush__c', Layout__c = 'RO & OAE', New_Value__c = 'false', 
                                                RecordTypeId = updateFieldRecordTypeId);
        actionList.add(newTaskAction2);
        
        Action__c newEmailAction = new Action__c(Name = 'Send Email', Auto_Task__c = newAutoTask.Id, Template_Name__c = 'Denied Task', Send_Email_From__c = 'Do Not Reply',
                                            Send_Email_To__c = 'Other', Recipient_s_Email_Address__c = 'test@email.com', RecordTypeId = sendEmailRecordTypeId);
        actionList.add(newEmailAction);
        
        Action__c newEmailAction2 = new Action__c(Name = 'Send Email 2', Auto_Task__c = newAutoTask.Id, Template_Name__c = 'ARSC Rush Case', Send_Email_From__c = 'Do Not Reply',
                                            Send_Email_To__c = 'Case Creator', RecordTypeId = sendEmailRecordTypeId);
        actionList.add(newEmailAction2);
        
        Action__c newEmailAction3 = new Action__c(Name = 'Send Email 3', Auto_Task__c = newAutoTask.Id, Template_Name__c = 'Internal Case Review', Send_Email_From__c = 'Do Not Reply',
                                            Send_Email_To__c = 'Case Owner', RecordTypeId = sendEmailRecordTypeId);
        actionList.add(newEmailAction3);
        
        Action__c newSurveyAction = new Action__c(Name = 'Send Survey', Auto_Task__c = newAutoTask.Id, Survey_Name__c = 'Test Survey',
                                            Send_Survey_To__c = 'Other', Recipient_s_Email_Address__c = 'test@email.com', RecordTypeId = sendSurveyRecordTypeId);
        actionList.add(newSurveyAction);
        
        Action__c newSurveyAction2 = new Action__c(Name = 'Send Survey 2', Auto_Task__c = newAutoTask.Id, Survey_Name__c = 'Test Survey2',
                                            Send_Survey_To__c = 'Case Creator', Recipient_s_Email_Address__c = 'test@email.com', RecordTypeId = sendSurveyRecordTypeId);
        actionList.add(newSurveyAction2);
        insert actionList;
        
    }
    
    static testMethod void getAutoTasksTest() {
        RunAutoTaskController_AC controller = new RunAutoTaskController_AC();
        List<Case> caseList = [SELECT Id FROM Case];
        String caseId = caseList[0].Id;
        Test.startTest();
        controller = RunAutoTaskController_AC.getAutoTasks(caseId);
        Test.stopTest();
        
        System.assertEquals(false, controller.autoTaskMap == null, 'Auto Task record not found.');
    }
    
    static testMethod void getTaskAndRunAutoTaskTest() {
        
        RunAutoTaskController_AC controller = new RunAutoTaskController_AC();
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User newUser = new User(Alias = 'utest', Email='test@email.com',
                                Emailencodingkey='UTF-8', FirstName='First', Lastname='Last', languagelocalekey='en_US',
                                Localesidkey='en_US', ProfileId = profile.Id, timezonesidkey='Europe/London', username='testSurveyProcess@myemail.com');
        insert newUser;
        
        List<PermissionSet> levelIIPM = [SELECT Id FROM PermissionSet WHERE Label = 'ROAE Update Resolved Case - Level II'];
        PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = levelIIPM[0].Id, AssigneeId = newUser.Id);
        insert psa;
        
        Test.startTest();
        System.runAs(newUser) {            
            List<Case> caseList = [SELECT Id FROM Case];
            List<Task> taskList = [SELECT Id, Subject FROM Task];
            List<Auto_Task__c> autoTaskList = [SELECT Id FROM Auto_Task__c];
            caseList[0].Status = 'Resolved';
            caseList[0].Last_Case_Comment__c = 'Test';
            update caseList;      
            
            controller = RunAutoTaskController_AC.getTaskAndRunAutoTask(caseList[0].Id, autoTaskList[0].Id,taskList[0].Id);
        }
        Test.stopTest();
        
        System.assertEquals(null, controller.hasError, 'Error encountered: ' + controller.errorMessage);
    }
    
    static testMethod void doesSurveyExistTest() {
        String userMessage;
        
        String sendSurveyRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.SEND_SURVEY_RT).getRecordTypeId();
        List<Action__c> actList = [SELECT Id, Survey_Name__c FROM Action__c WHERE RecordTypeId =: sendSurveyRecordTypeId];
        
        Test.startTest();
        userMessage = RunAutoTaskController_AC.doesSurveyExist(actList[0]);
        Test.stopTest();
        
        System.assertEquals(false, String.isEmpty(userMessage), 'User message was empty. Survey found.');
    }
    
    static testMethod void catchExceptionTest() {
        RunAutoTaskController_AC controller = new RunAutoTaskController_AC();
        String ARSCRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('ARSC').getRecordTypeId();
        String updateFieldRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.UPDATE_FIELD_RT).getRecordTypeId();
        
        List<Case> testCase = [SELECT ID FROM Case];
        
        Auto_Task__c newAutoTask = new Auto_Task__c(Name = 'AutoTask-0000');
        insert newAutoTask;
        
        Action__c caseAction = new Action__c(Name = 'Test Action', Auto_Task__c = newAutoTask.Id, Field_To_Update__c = 'Status', Object__c = 'Case',
                                            Field_To_Update_API_Name__c = 'Invalid_Field__z', Layout__c = 'ARSC Read Only', New_Value__c = 'Pending', 
                                            RecordTypeId = updateFieldRecordTypeId);
        insert caseAction;
        
        Test.startTest();
    	controller = RunAutoTaskController_AC.runAutoTasks(testCase[0].Id, newAutoTask.Id, null, false);
        Test.stopTest();
        
        System.assertEquals(true, controller.hasError, 'An error was NOT encountered.');
    }
    
    static testMethod void queryAndUpdateRecordTest() {
        String updateFieldRecordTypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(RecordTypeConstants_AC.UPDATE_FIELD_RT).getRecordTypeId();
        
        List<Case> testCase = [SELECT ID FROM Case];
        List<Action__c> actList = [SELECT Id, Field_To_Update_API_Name__c, New_Value__c FROM Action__c WHERE RecordTypeId =: updateFieldRecordTypeId AND Name = 'Test Action'];
        
        Test.startTest();
        RunAutoTaskController_AC.queryAndUpdateRecord(actList, testCase[0], 'Case', false);
        Test.stopTest();
    }
}